### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by alistairholmes** [flutterdevzim/CoVID-19-Tracker#1]
![covid](https://user-images.githubusercontent.com/22801227/77664101-866fdc00-6f86-11ea-80a5-7cf1e7a58834.PNG)

- [x] 8.1 Get Current Date
- [x] 8.2 Card that will link to Self Check Screen
- [x] 8.3 Latest News - Link to news page
- [x] 8.4 Row to display Covid Cases, Recoveries, Deaths.
- [x] 8.5 Text For Prevention screen
- [x] 8.6 Connect to API to display current Cases, Recoveries, Deaths.
- [x] 8.7 Remove notification icon and replace with Info icon to link to About Page

**Comment by alistairholmes** [comment]
Guys I think we should just display info and cases for Zims

**Comment by DonnC** [comment]
sounds great, and SA too i think its an add on since we are almost in sync with what happens there.
But ZIM has higher priority

**Comment by DonnC** [comment]
Objectives met in response to hack4Covid Hackathon
Closing issue
