### ISSUE TITLE
Preventative Measures Screen

### ISSUE THREAD

**Issue by alistairholmes** [flutterdevzim/CoVID-19-Tracker#5]
A Screen that will provide information on what on needs to do to prevent contracting or spreading the virus.

**Comment by DonnC** [comment]
Proposed UI design

![image](https://user-images.githubusercontent.com/47761288/78936822-996acc00-7aaf-11ea-9755-9e8227eb53cb.png)

**Comment by alistairholmes** [comment]
So glad this is done!!! -> [Reference Code](https://github.com/flutterdevzim/CoVID-19-Tracker/commit/c070e3e18222781657d560546af2e5705954cdca)
