### ISSUE TITLE
About Screen

### ISSUE THREAD

**Issue by alistairholmes** [flutterdevzim/CoVID-19-Tracker#6]
About Screen that will provide info about the reason we made the app.
List all contributors to the project.
Where more info can be found about co-vid.
Libraries used in the app.
Feature request / Bug reporting

**Comment by DonnC** [comment]
> About Screen that will provide info about the reason we made the app.
> List all contributors to the project.
> Where more info can be found about co-vid.
> Libraries used in the app.
> Feature request / Bug reporting

About page created in response to hackathon
